# Generated by Django 3.1 on 2022-11-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20221122_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('brand', 'brand')], max_length=100),
        ),
    ]
